---
#========================================================================
# Copyright Universidade Federal do Espirito Santo (Ufes)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
# This program is released under license GNU GPL v3+ license.
#
#========================================================================
version: '3.8'

services:
  # 1. O Banco de Dados (Imagem Oficial Pura)
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    user: root  # <--- ADICIONE ESTA LINHA AQUI
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    ports:
      - "8000:8000"
    volumes:
      - ./dbdata:/home/dynamodblocal/data
    networks:
      - dynamo-net

  # 2. O Inicializador (Roda uma vez e morre)
  dynamodb-init:
    build: ./init
    container_name: dynamodb-init
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      AWS_DEFAULT_REGION: us-west-2
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
    networks:
      - dynamo-net

  # 3. Interface Visual (Opcional, mas útil)
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
    depends_on:
      - dynamodb-local
    networks:
      - dynamo-net

  # 4. Sua Aplicação Python (Opcional: rodar via container)
  app-client:
    build: ./app
    container_name: app-client
    stdin_open: true
    tty: true
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
    depends_on:
      - dynamodb-init
    volumes:               # <--- ADICIONE ISSO
      - ./app:/app         # <--- ADICIONE ISSO
    networks:
      - dynamo-net

networks:
  dynamo-net:
    driver: bridge